# Generated by Django 4.0.4 on 2022-06-21 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('idMarca', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id marca')),
                ('nombreMarca', models.CharField(max_length=20, verbose_name='Nombre marca')),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False, verbose_name='Id producto automatica')),
                ('nombreProducto', models.CharField(max_length=50, verbose_name='Nombre del producto/modelo')),
                ('precio', models.IntegerField(max_length=10, verbose_name='Precio del producto')),
                ('stock', models.IntegerField(max_length=3, verbose_name='Stock producto')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.marca')),
            ],
        ),
        migrations.CreateModel(
            name='detalle_compra',
            fields=[
                ('idCompra', models.AutoField(primary_key=True, serialize=False, verbose_name='Orden de compra')),
                ('montoCompra', models.IntegerField(max_length=10, verbose_name='Total compra')),
                ('producto', models.ManyToManyField(to='core.productos')),
            ],
        ),
    ]
