# Generated by Django 4.0.4 on 2022-06-21 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_detalle_compra_montocompra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='idMarca',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id marca'),
        ),
    ]
